import type { Metadata } from "next";
import { Geist, Geist_Mono, Nanum_Gothic } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "@/components/common/Header";
import { Footer } from "@/components/common/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const nanumGothic = Nanum_Gothic({
    weight: ["400", "700", "800"],
    subsets: ["latin"],
    variable: "--font-nanum-gothic",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const pretendard = localFont({
    src: [
        {
            path: "../../node_modules/pretendard/dist/web/static/woff2/Pretendard-Regular.woff2",
            weight: "400",
        },
        {
            path: "../../node_modules/pretendard/dist/web/static/woff2/Pretendard-Medium.woff2",
            weight: "500",
        },
        {
            path: "../../node_modules/pretendard/dist/web/static/woff2/Pretendard-SemiBold.woff2",
            weight: "600",
        },
        {
            path: "../../node_modules/pretendard/dist/web/static/woff2/Pretendard-Bold.woff2",
            weight: "700",
        },
        {
            path: "../../node_modules/pretendard/dist/web/static/woff2/Pretendard-ExtraBold.woff2",
            weight: "800",
        },
    ],
    variable: "--font-pretendard",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} ${nanumGothic.variable} ${pretendard.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <div className="relative mx-auto min-h-dvh max-w-[390px] overflow-hidden bg-white flex flex-col">
                    <Header />
                    <main className="flex-1 overflow-y-auto pt-15 pb-20">{children}</main>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
